[package]
name = "influxdb3_load_generator"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Core Crates
observability_deps.workspace = true
trogging.workspace = true
influxdb_iox_client.workspace = true

# Local Deps
influxdb3_client = { path = "../influxdb3_client" }
influxdb3_process = { path = "../influxdb3_process", default-features = false }

# crates.io Dependencies
anyhow.workspace = true
arrow.workspace = true
arrow-array.workspace = true
arrow-flight.workspace = true
bytes.workspace = true
chrono.workspace = true
clap.workspace = true
csv.workspace = true
dotenvy.workspace = true
humantime.workspace = true
num.workspace = true
parking_lot.workspace = true
rand.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
sysinfo.workspace = true
thiserror.workspace = true
tokio.workspace = true
tonic.workspace = true
url.workspace = true

[lints]
workspace = true
