[package]
name = "influxdb3_sys_events"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true


[dependencies]
# core crates
iox_time.workspace = true
iox_system_tables.workspace = true

# local deps
influxdb3_server = { path = "../influxdb3_server" }

# crates.io deps
arrow.workspace = true
arrow-array.workspace = true
async-trait.workspace = true
bevy_reflect.workspace = true
chrono.workspace = true
dashmap.workspace = true
datafusion.workspace = true

[dev-dependencies]
test-log.workspace = true
proptest.workspace = true
